# Generated by Django 5.1.2 on 2024-10-27 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji_per_day', models.IntegerField(choices=[(1, '1'), (2, '2'), (5, '5'), (10, '10')], default=5)),
                ('duration_in_days', models.IntegerField(choices=[(7, '7 Days'), (14, '14 Days'), (30, '30 Days'), (60, '60 Days')], default=14)),
                ('email_time', models.TimeField()),
                ('subscribed', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
